server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://xrspjyhuawghpf:89dc1b866ae551b5d1219794254851a2d3aa47db06377adc5455ef16e63f10c7@ec2-34-193-113-223.compute-1.amazonaws.com:5432/dcrdho11dfsj2p
    username: xrspjyhuawghpf
    password: 89dc1b866ae551b5d1219794254851a2d3aa47db06377adc5455ef16e63f10c7
  jpa:
    show-sql: true
    database-plataform: org.hibernate.dialect.PostgresSQLDialect
    gererate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto Criado para o Bootcamp DIO - Santander / Back-End
  version: 1.1.1
